---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

extraEnvs:
  - name: ELASTIC_PASSWORD
    value: "YY_21eFpsgLCFVkmEHLr"

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 30Gi