---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "node-fluentd-service"
  namespace: "logging"
  labels:
    app: "node-fluentd"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: "node-fluentd"
  type: "LoadBalancer"