apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-uat
spec:
  acme:
    email: lutfi.maulana@ecomindo.com
    privateKeySecretRef:
      name: letsencrypt-uat
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            podTemplate:
              metadata:
                annotations:
                  kuma.io/sidecar-injection: "false" # If ingress is running in Kuma/Kong Mesh, disable sidecar injection
                  sidecar.istio.io/inject: "false" # If using Istio, disable sidecar injection
            class: kong
